/**
 * Implements hook_libraries_info().
 */
function mixitup_library_libraries_info() {
  $libraries = array();
  $libraries['mixitup'] = array(
    'name' => 'MixItUp',
    'vendor url' => 'https://mixitup.kunkalabs.com/',
    'download url' => 'https://github.com/patrickkunka/mixitup',
    'version arguments' => array(
      'file' => 'jquery.mixitup.min.js',
      // MixItUp v2.1
      'pattern' => '/MixItUp v(\d+\.+\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.mixitup.min.js',
      ),
    ),
  );

  return $libraries;
}
